# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: ""

image:
  repository: lucarocco97
  pullPolicy: Always
  name: liqo-dashboard

tls:
  secretName: ""

backend:
  port: 8080
  deployment:
    imageTag: backend-v1
    replicas: 1
    args:
    - --v=9
    env: []
  ingress:
    annotations: {}
    path: /api
  service:
    type: NodePort

frontend:
  deployment:
    imageTag: frontend-v1
    replicas: 1
  ingress:
    annotations: {}
    path: /
    service:
      port: 8080
  service:
    type: NodePort
    ports:
    - port: 8080